version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - echo Installing angular cli...
      - npm install -g @angular/cli
  build:
    commands:
      - echo Build started...
      - ng build --prod
      - npm install express path --save
      - npm install
artifacts:
  files:
    - dist/**/*
    - server.js
    - package.json
